version: '3.9'

services:
  search_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads

  asreview:
    image: "ghcr.io/asreview/asreview:v1.6.2"
    volumes:
      - ${HOME}/Documents/Search_AsReview_Docker/project_folder:/project_folder  # Bind mount for persistent data
      - ./asreview_config.toml:/app/asreview_config.toml
    environment:
      - ASREVIEW_LAB_API_URL=/
      - ASREVIEW_LAB_CONFIG_PATH=/app/asreview_config.toml
      - ASREVIEW_PATH=/project_folder  # Set ASREVIEW_PATH for project folder
    ports:
      - "5001:5001"
    entrypoint: /bin/sh -c "mkdir -p /project_folder && exec asreview lab --port 5001 --host 0.0.0.0"

  server:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./asreview.conf:/etc/nginx/nginx.conf
    depends_on:
      - asreview
