version: '3.8'
services:
  asreview:
    image: "ghcr.io/asreview/asreview:v1.6.2"
    volumes:
      - ~/asreview:/project_folder
      - ./asreview_config.toml:/app/asreview_config.toml
    environment:
      - ASREVIEW_LAB_API_URL=/
      - ASREVIEW_LAB_CONFIG_PATH=/app/asreview_config.toml
    ports:
      - ${BACKEND_EXTERNAL_PORT}:5006
    entrypoint: []
    command: >
      bash -c "asreview auth-tool create-db
      && gunicorn -w ${WORKERS} -b \"0.0.0.0:5006\" \"asreview.webapp.app:create_app()\""

  server:
    image: nginx
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:80
    volumes:
      - ./asreview.conf:/etc/nginx/nginx.conf
    depends_on:
      - asreview

volumes:
  project-folder:
